// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7B6khNioU7q2P5cz07uLbtDDa7ObuHos',
    appId: '1:242217460408:web:1a6bbd2d053e1a9c200a4d',
    messagingSenderId: '242217460408',
    projectId: 'vehicle-services0',
    authDomain: 'vehicle-services0.firebaseapp.com',
    storageBucket: 'vehicle-services0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXFrxTraBqkJf01ELcQBc9FimCy6E-P8M',
    appId: '1:242217460408:android:ceda9156851301bb200a4d',
    messagingSenderId: '242217460408',
    projectId: 'vehicle-services0',
    storageBucket: 'vehicle-services0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJByrVsD5TbwzZeB8ZqyofzD_Tq0rl1uU',
    appId: '1:242217460408:ios:3af62fefba67e012200a4d',
    messagingSenderId: '242217460408',
    projectId: 'vehicle-services0',
    storageBucket: 'vehicle-services0.firebasestorage.app',
    iosBundleId: 'com.example.vehiclex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJByrVsD5TbwzZeB8ZqyofzD_Tq0rl1uU',
    appId: '1:242217460408:ios:3af62fefba67e012200a4d',
    messagingSenderId: '242217460408',
    projectId: 'vehicle-services0',
    storageBucket: 'vehicle-services0.firebasestorage.app',
    iosBundleId: 'com.example.vehiclex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7B6khNioU7q2P5cz07uLbtDDa7ObuHos',
    appId: '1:242217460408:web:b80b7c8ee7192e82200a4d',
    messagingSenderId: '242217460408',
    projectId: 'vehicle-services0',
    authDomain: 'vehicle-services0.firebaseapp.com',
    storageBucket: 'vehicle-services0.firebasestorage.app',
  );
}
